[package]
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
edition = "2021"
name = "foxtrot"
version = "0.2.0"
license = "MIT OR Apache-2.0"
exclude = [
    "dist",
    "build",
    "assets",
    "credits",
    "saves",
    "resources",
    "build.rs",
]
description = "The all-in-one Bevy 3D game template."
repository = "https://github.com/janhohenheim/foxtrot"
keywords = ["gamedev", "bevy", "template", "game"]
categories = ["game-development"]
homepage = "https://janhohenheim.github.io/foxtrot/"

[features]
default = ["dev"]
dev = ["dep:bevy_editor_pls", "dep:bevy_prototype_debug_lines"]
tracing = ["bevy/trace_chrome"]

[dependencies]
bevy_kira_audio = "0.18"
bevy_asset_loader = { version = "0.19", features = ["progress_tracking"] }
bevy_common_assets = { version = "0.9", features = ["ron", "toml"] }
bevy_egui = "0.24"
serde = { version = "1", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
strum = "0.25"
strum_macros = "0.25"
ron = "0.8"
regex = "1"
chrono = "0.4"
glob = "0.3"
oxidized_navigation = "0.8"
bitflags = "2"
iyes_progress = "0.10"
unicode-segmentation = "1"
anyhow = "1"
leafwing-input-manager = { version = "0.11", features = ["egui"] }
warbler_grass = "0.4"
rand = { version = "0.8", features = ["small_rng", "nightly"] }
bevy_dolly = "0.0.2"
spew = "0.4"
bevy_mod_sysfail = "5"
seldom_fn_plugin = "0.5"
bevy_rapier3d = { version = "0.23", features = [ "serde-serialize", "simd-stable" ] }
bevy_editor_pls = { version = "0.7", optional = true }
bevy_prototype_debug_lines = { version = "0.11", optional = true, features = [ "3d" ] }

# keep the following in sync with Bevy's dependencies
## https://github.com/bevyengine/bevy/blob/v0.12.1/crates/bevy_winit/Cargo.toml#L31
winit = { version = "0.28.7", default-features = false }
## https://github.com/bevyengine/bevy/blob/v0.12.1/crates/bevy_render/Cargo.toml#L57
image = { version = "0.24", default-features = false }

[dependencies.bevy]
version = "0.12"
default-features = false
features = [
    "animation",
    "bevy_asset",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "png",
    "jpeg",
    "hdr",
    "zstd",
    "x11",
    "ktx2",
    "tonemapping_luts",
    "serialize",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.12"
default-features = false
features = [ "file_watcher" ]


[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies.bevy]
version = "0.12"
default-features = false
features = [ "dynamic_linking" ]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy_hanabi = "0.9"
bevy_rapier3d = { version = "0.23.0", features = ["parallel"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
bevy_rapier3d = { version = "0.23.0", features = ["wasm-bindgen"] }

[build-dependencies]
embed-resource = "2"
